/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux AHM-2022 5.15.90.1-microsoft-standard-WSL2 x86_64"
#define LGL_COMPILED "Thu Oct 26 04:14:15 ADT 2023"
#define LGL_RELEASED "Don Mai 22 22:08:00 CEST 2014"
#define LGL_VERSION "azf"
#define LGL_ID "92032848c138b2f33629ad24394d60a3787a1046"
